In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns

In [107]:
df = pd.read_csv('https://raw.githubusercontent.com/DAVE3625/Dave3625-2026/refs/heads/main/Lab2/data/stud.csv', sep=',')

df.head()

   StudentID  Age              email hrsStudy  FinalGrade
0      47412   20  s47412@oslomet.no        5        46.0
1      15077   22  s15077@oslomet.no        0        65.0
2      15467   27  s15467@oslomet.no        1        26.0
3      17907   21  s17907@oslomet.no        6        68.0
4      13352  333  s13352@oslomet.no        4        34.0

In [108]:
df.describe()

          StudentID  FinalGrade
count     50.000000   49.000000
mean   48969.820000   71.653061
std    26870.066326   90.455917
min    10736.000000   24.000000
25%    26666.500000   39.000000
50%    44292.000000   60.000000
75%    70400.250000   78.000000
max    99823.000000  673.000000

In [ ]:
df = df.replace(r'^\s*$', np.nan, regex=True)
df = df.dropna(inplace=True)

df['hrsStudy'] = df['hrsStudy'].astype('int32')
df['Age'] = df['Age'].astype('int32')
df['email'] = df['email'].astype('object')

AttributeError: 'NoneType' object has no attribute 'replace'

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   47 non-null     int64
 1   Age         47 non-null     int32
 2   email       47 non-null     object
 3   hrsStudy    47 non-null     int32
 4   FinalGrade  47 non-null     float64
dtypes: float64(1), int32(2), int64(1), object(1)
memory usage: 1.8+ KB